language: python
cache: pip
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - TEST_TYPE="test"
  - TEST_TYPE="test_sympy"
matrix:
  include:
    - python: 3.6
      env: TEST_TYPE="compliance"
install:
  - pip install .
script:
  - if [ "$TEST_TYPE" == "compliance" ] ; then pip install .[dev]; pre-commit run --all-files ; fi
  - if [ "$TEST_TYPE" == "test" ] ; then cd tests; py.test ; fi
  - if [ "$TEST_TYPE" == "test_sympy" ] ; then pip install sympy; cd tests; py.test ; fi
