language: python
cache: pip
python:
  - "3.7"
  - "3.8"
env:
  - TEST_TYPE="test"
  - TEST_TYPE="test_sympy"
matrix:
  include:
    - python: 3.7
      env: TEST_TYPE="compliance"
install:
  - pip install .
  - pip install codecov
  - pip install pytest-cov
script:
  - if [ "$TEST_TYPE" == "compliance" ] ; then pip install .[dev]; pre-commit run --all-files ; fi
  - if [ "$TEST_TYPE" == "test" ] ; then pytest --cov=fsc.hdf5_io --cov-config=.coveragerc ; fi
  - if [ "$TEST_TYPE" == "test_sympy" ] ; then pip install sympy; pytest --cov=fsc.hdf5_io --cov-config=.coveragerc  ; fi
after_success:
  - codecov
